# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios


1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
#instalar numpy
!pip install numpy

In [3]:
#Importar numpy
import numpy as np

In [12]:
#1. Crear un arreglo de ceros de longitud 12
array1=np.zeros(12)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [75]:
#2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array2=np.zeros(10)
array2[4] = 10
print(array2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
array2b[0, 4] = 5
print(array2)
print(array2b)

In [13]:
#3. Crear un arreglo que tenga los números del 10 al 49
array3=np.arange(10,50,1)
print (array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [61]:
#4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array4=np.arange(0,9,1)
array4.shape= (3, 3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array8=np.random.randn(100)
print (array8)
print(np.mean(array8))
print(np.var(array8))

[-0.79815981 -1.54208076  0.27095062 -0.36242183  0.94633237 -0.79965838
  0.64418478 -0.0141446  -1.09007668 -0.29302438 -0.3017723   1.26251937
 -2.33378172  0.52031331  0.64080851  0.73542973  0.43455234 -1.0518697
 -0.88729444  1.15846506 -1.71819287  0.14670598 -1.0434892   0.1485386
 -1.27462801  0.62805427  0.97025981 -0.8256647   1.33483987  3.02658259
 -0.29593648  0.61292728  0.75358943  0.94403302  0.88263223  1.2661629
 -0.40270498  0.24519369 -0.05715379  1.95819428 -0.00457267 -1.32571253
 -1.2585871   0.28264501  1.00416936 -1.31135343  0.40211229 -0.21387411
 -0.24606317 -1.4840965   0.29214493 -1.38709143 -0.77367704  0.36882398
 -0.76393551  0.88643709  0.0933831   0.04071193 -1.1469161   0.99620665
 -0.89788197  1.14000497 -0.47734442 -1.08215178 -0.82946769 -0.00580221
 -0.24636249  0.50486724 -0.48607198 -0.43121897  1.26008675  1.6580176
 -2.13753089 -0.94720131 -0.29860903  0.52976809  0.45866495 -0.69354416
 -2.08571673 -0.63844221 -0.86976852 -0.86128482 -1.741

In [21]:
#6. Calcular la media de un arreglo usando np.sum
array6=np.array([2, 4, 6])
prom=np.sum(array6)//len(array6) 
print(array6)
print(prom)

[ 2  4 12]
6


In [56]:
#7. Calcular la varianza de un arreglo usando np.sum y np.mean
#Var (X) = [(x1-x̄)2+ (x2-x̄)2+ (x3-x̄)2+…….+(xn-x̄)2]/n
array7=np.array([2, 4, 6])
array7_mean=np.mean(array7)
array7_dif=[i - array7_mean for i in array7]
array7_sum_cuad=np.sum([i ** 2 for i in array7_dif])
array7_var=format(array7_sum_cuad//len(array7),".2f")
print(array7_mean)
print(np.mean(array7))
print(array7_dif)
print(array7_sum_cuad)
print(len(array7))
print(array7_var)
  
print(np.var(array7))
print("La varianza del arreglo es:",array7_var)  

4.0
4.0
[-2.0, 0.0, 2.0]
8.0
3
2.00
2.6666666666666665
La varianza del arreglo es: 2.00


In [ ]:
array7_var=(np.sum((array7**2))//len(array7))-(np.mean(array7))
rounded_number = format(number,".2f" )

In [ ]:
#8. Crear un array de números aleatorios usando np.random.randn
array8=np.random.randn(10)
print (array8)